### ISSUE TITLE
Bot setting up 2-factor auth problem

### ISSUE THREAD

**Issue by igorkurochka** [zulurepublic/liteIM-telegram#1]
I'm trying to set up bot and stuck on entering my phone number to set up two factor auth. 
I have a phone with Bulgaria code country, it's something like +359887776655
The bot just keep asking me to enter a phone after I entered it. I suppose it has trouble with understanding phones from countries other than those have a one-digit code.

**Comment by majestic84** [comment]
Hi There,

Thanks for reaching out. We'll be releasing a patch today that may help the issue you're having. I will let you know when that is ready so you can give it another try.

**Comment by frankyhanky** [comment]
Can't sign in 2FA. I try this, +countrynumber.
Example +xx15912345678.
Bot=> no valid number.

**Comment by majestic84** [comment]
Hi @frankyhanky it may be the same issue. I'll let you know when we have the new version running in production so you can try again.

**Comment by ELON-HARA** [comment]
Hi everyone
I tryng to set up a 2FA, but after enter correctly the data, now i getting a message
"Sorry, but that phone number is already registered. Please try again with a different number."
If I try to restart the Bot, it asks for the phone number again.

**Comment by majestic84** [comment]
@igorkurochka @frankyhanky Please try now and let me know.

@ELON-HARA please DM me your email address and phone number at /u/majestic84 on reddit.

**Comment by igorkurochka** [comment]
@majestic84 
tried again, new trouble.
1. I've sent my phone and my password next to it. success. the bot responded that they sent me a code and asked to send the code and my password. *but no sms received*.
2. after coupe hours I've decided to try again and hit the only option I have "change phone number".
I've sent my phone number (all the same, I've got no others). and this time bot responded with error "Sorry, but that phone number is already registered. Please try again with a different number."

**Comment by frankyhanky** [comment]
@majestic84 well done.
Next problem, i have received litcoins on the lite.im wallet confirm 6/6 but can`t send Litecoin to an other wallet like example loaf.
bot=> sorry, i had an issue with your request. Please try again.
I try again and again => always the same report.

**Comment by majestic84** [comment]
@igorkurochka the problem you had should be resolved as of today. Please try again and let me know. Please also note that it is no longer required to send both the code and your password at once -- those fields have been divided into their own steps.

@frankyhanky you may have had a similar issue. I deployed a patch today that can resolve several different problems with inconsistencies that may have occurred during the signup process. Please try again and let me know how it goes.

**Comment by frankyhanky** [comment]
@majestic84 Step back to issue one.
Can't sign in 2FA. I try this, +countrynumber.
Example +xx15912345678.
Bot=> no valid number.

**Comment by majestic84** [comment]
@frankyhanky I may have to use a different e164 phone number validator. Would you be so kind to DM me the full phone number you are trying to register with on Reddit - /u/majestic84

**Comment by frankyhanky** [comment]
@majestic84 i don`t wont present my number with DM on reddit.
It was possible to sent coins to the lite.im wallet, because i was logged in.
bot=> received coins.
Now the bot can`t valid my phone number.
here is an example of my number:
+49151xxxxxxxx   
country code 1-3 digit
At all 14digit
Max 15 digit

**Comment by majestic84** [comment]
@frankyhanky I will be happy to assist you, but I will need to have the full number you are trying to register with. I recommended DMing me on Reddit since that is more private than posting it on here.

**Comment by frankyhanky** [comment]
@majestic84 thx for recommended DMing you on Reddit, but i don`t thrust Reddit - has just been hacked. We must find another secure way.
Do not understand why you need my full number, please tell me.
Could the error be due to the settings in the messenger or phone?

**Comment by majestic84** [comment]
@frankyhanky I am asking you for your full phone number so I could test the phone number validation method with the same value you are using. I want to test the exact case that is causing you an issue, having a partial phone number does not help me complete that.
