### ISSUE TITLE
Question about the architecture

### ISSUE THREAD

**Issue by sidneibjunior** [zulurepublic/liteIM-telegram#3]
I'm looking into the source code and trying to understand the architecture.
I saw that the bot integrates with Firestore database to read and make transactions.
What I couldn't figure out is: how does it integrates to the Litecoin blockchain to read / save the data?

Is there a documentation explaining the whole system architecture?

Thanks in advance,
Sidnei Bernardo Junior

**Comment by thisisvilla** [comment]
Hello @sidneibjunior 

Our API handles all communication with the blockchain and writing to Firebase.

Hope that helps! :)
